import AsyncStorage from
  '@react-native-async-storage/async-storage';

import React, {
  useEffect,
  useState,
} from 'react';

import {
  ActivityIndicator,
  Alert,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';

import SimpleCameraStream from
  '../../components/SimpleCameraStream';

import { config } from '../../config';

function normalizeServerUrl(value: string) {
  return value.trim().replace(/\/+$/, '');
}

export default function CameraScreen() {
  const [isLoading, setIsLoading] =
    useState(true);

  const [isPaired, setIsPaired] =
    useState(false);

  const [cameraId, setCameraId] =
    useState('');

  const [serverUrl, setServerUrl] =
    useState('');

  const [inputCameraId, setInputCameraId] =
    useState('');

  const currentConfiguredServerUrl =
    normalizeServerUrl(config.serverUrl);

  useEffect(() => {
    const loadConfig = async () => {
      try {
        const savedCameraId =
          await AsyncStorage.getItem('cameraId');

        const savedServerUrl =
          await AsyncStorage.getItem('serverUrl');

        console.log('📱 Saved camera config:', {
          savedCameraId,
          savedServerUrl,
          currentConfiguredServerUrl,
        });

        if (savedCameraId) {
          /*
           * Always prefer the latest .env/config URL.
           * This prevents an old hotspot IP remaining saved.
           */
          if (
            savedServerUrl !==
            currentConfiguredServerUrl
          ) {
            console.log(
              '🔄 Migrating saved server URL:',
              savedServerUrl,
              '→',
              currentConfiguredServerUrl,
            );

            await AsyncStorage.setItem(
              'serverUrl',
              currentConfiguredServerUrl,
            );
          }

          setCameraId(savedCameraId);
          setServerUrl(
            currentConfiguredServerUrl,
          );
          setIsPaired(true);
        }
      } catch (error) {
        console.error(
          '❌ Failed to load camera config:',
          error,
        );
      } finally {
        setIsLoading(false);
      }
    };

    loadConfig();
  }, [currentConfiguredServerUrl]);

  const handlePair = async () => {
    const normalizedCameraId =
      inputCameraId.trim();

    if (!normalizedCameraId) {
      Alert.alert(
        'Camera ID required',
        'Enter the camera ID shown by the dashboard.',
      );

      return;
    }

    try {
      await AsyncStorage.multiSet([
        ['cameraId', normalizedCameraId],
        [
          'serverUrl',
          currentConfiguredServerUrl,
        ],
      ]);

      setCameraId(normalizedCameraId);
      setServerUrl(
        currentConfiguredServerUrl,
      );
      setIsPaired(true);

      Alert.alert(
        'Camera paired',
        'The smartphone camera is ready.',
      );
    } catch (error) {
      console.error(
        '❌ Camera pairing failed:',
        error,
      );

      Alert.alert(
        'Pairing failed',
        'The camera settings could not be saved.',
      );
    }
  };

  const handleUnpair = async () => {
    try {
      await AsyncStorage.multiRemove([
        'cameraId',
        'serverUrl',
      ]);

      setCameraId('');
      setServerUrl('');
      setInputCameraId('');
      setIsPaired(false);

      Alert.alert(
        'Camera unpaired',
        'This phone is no longer paired.',
      );
    } catch (error) {
      console.error(
        '❌ Camera unpair failed:',
        error,
      );
    }
  };

  if (isLoading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator
          size="large"
          color="#10B981"
        />

        <Text style={styles.loadingText}>
          Loading camera configuration...
        </Text>
      </View>
    );
  }

  if (!isPaired) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.title}>
          📱 Pair Smartphone Camera
        </Text>

        <View style={styles.inputContainer}>
          <Text style={styles.label}>
            Camera ID
          </Text>

          <TextInput
            style={styles.input}
            placeholder="cam-1783751732915"
            value={inputCameraId}
            onChangeText={setInputCameraId}
            autoCapitalize="none"
            autoCorrect={false}
          />
        </View>

        <TouchableOpacity
          style={styles.pairButton}
          onPress={handlePair}
        >
          <Text style={styles.buttonText}>
            Pair Camera
          </Text>
        </TouchableOpacity>

        <View style={styles.infoBox}>
          <Text style={styles.infoText}>
            Enter the camera ID generated by the
            dashboard.
          </Text>

          <Text style={styles.infoText}>
            Server: {currentConfiguredServerUrl}
          </Text>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.streamContainer}>
      <SimpleCameraStream
        cameraId={cameraId}
        serverUrl={serverUrl}
      />

      <View style={styles.infoBar}>
        <Text style={styles.infoBarText}>
          📹 CCTV camera active
        </Text>

        <Text style={styles.infoBarText}>
          ID: {cameraId}
        </Text>

        <Text style={styles.infoBarText}>
          Server: {serverUrl}
        </Text>
      </View>

      <TouchableOpacity
        style={styles.unpairButton}
        onPress={handleUnpair}
      >
        <Text style={styles.buttonText}>
          Unpair Camera
        </Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#1A1A2E',
  },

  streamContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },

  loadingText: {
    color: '#FFFFFF',
    fontSize: 15,
    marginTop: 14,
  },

  title: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 30,
  },

  inputContainer: {
    width: '100%',
    marginBottom: 20,
  },

  label: {
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 8,
  },

  input: {
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
  },

  pairButton: {
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 8,
    marginBottom: 20,
    backgroundColor: '#10B981',
  },

  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },

  infoBox: {
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3B82F6',
    backgroundColor: 'rgba(59,130,246,0.1)',
  },

  infoText: {
    color: '#93C5FD',
    fontSize: 12,
    marginBottom: 5,
  },

  infoBar: {
    position: 'absolute',
    right: 0,
    bottom: 80,
    left: 0,
    padding: 15,
    backgroundColor: 'rgba(0,0,0,0.72)',
  },

  infoBarText: {
    color: '#10B981',
    fontSize: 13,
    marginBottom: 4,
  },

  unpairButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    left: 20,
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#EF4444',
  },
});